#!/bin/bash
for filename in "$@"
do echo '<!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>git '$filename'</title>
    <link rel="stylesheet" href="../styles/global.css">
  </head>
  <body>
  <nav>
    <a href="../index.html">wiki</a> &gt
    <a href="index.html">git</a> &gt
    <a href="'$filename.html'">'$filename'</a>
  </nav>
    <h1>git '$filename'</h1>
    <ul>
    </ul>
  </body>
  </html>' > $filename.html
  sed -i "s|</ul>|<li><a href=\"$filename.html\">git $filename</a></li>\n</ul>|" index.html
done
