#!/bin/bash

for filename in "$@"
do echo '<!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>&lt'$filename'&gt</title>
    <link rel="stylesheet" href="../../styles/global.css">
  </head>
  <body>
    <h1>&lt'$filename'&gt;&lt/'$filename'&gt</h1>
    <ul>
      <li></li>
    </ul>
    <footer>
      <a href="../../index.html">wiki</a> &gt <a href="../index.html">html</a> &gt <a href="index.html">tags</a> &gt <a href="'$filename.html'">'$filename'</a>
    </footer>
  </body>
  </html>' > $filename.html
done
